version: "3"
services:
  db:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=zabei
      - POSTGRES_PASSWORD=FnNa9ZZTkIfqEE5
      - POSTGRES_DB=zabei
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - data:/var/lib/postgresql/data
  main:
    build: .
    ports:
      - 80:8090
    environment:
      SPRING_PROFILES_ACTIVE: test
    depends_on:
      - db
    volumes:
      - img:/img
volumes:
  data:
  img: