server:
  port: 8090
  servlet:
    session:
      timeout: 90d
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/zabei
    #    url: jdbc:h2:file:./data/demo
    username: zabei
    password: FnNa9ZZTkIfqEE5
  #    initialization-mode: always
  #    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  #  h2:
  #    console:
  #      enabled: true
  #      path: /console
  security:
    basic:
      enabled: true
      authorize-mode: NONE
    application:
      name: zabei
  thymeleaf:
    cache: false
    prefix: classpath:/templates
  #    check-template-location: true
  servlet:
    multipart:
      max-file-size: 10MB
max-request-size: 10MB