server:
  port: 8090
  servlet:
    session:
      timeout: 90d
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ojnhqmfciizurc:dd39f2a3eec6842d939e41ad7f417daa1aee36a63cc954bb04bab188c30899ec@ec2-79-125-4-72.eu-west-1.compute.amazonaws.com:5432/dbf2u2m4u3al8s
#    url: jdbc:h2:file:./data/demo
    username: ojnhqmfciizurc
    password: dd39f2a3eec6842d939e41ad7f417daa1aee36a63cc954bb04bab188c30899ec
#    initialization-mode: always
#    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#  h2:
#    console:
#      enabled: true
#      path: /console
  security:
    basic:
      enabled: true
      authorize-mode: NONE
    application:
      name: restaurant
  thymeleaf:
    cache: false
    prefix: classpath:/templates
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
